### ISSUE TITLE
Is this a WIP 

### ISSUE THREAD

**Issue by woakes070048** [TheDMSGroup/mautic-eb#1]
Hello,

We just found this and it looks like a great job and we are looking at using it.  Is it ready for a production environment and if not how can we help? 

Thanks for your time 

William

**Comment by heathdutton** [comment]
Sorry for the late reply, yes it is still a WIP.

I am testing this in a couple pre-production environments, but I expect to do a great deal more tweaking on it in early 2018. I'm just getting started here.

That being said, if you want to go ahead and use this repo as a basis for using Mautic in Elastic Beanstalk, by all means, do so! It should save some time. You might want to fork since I'm still running around with a machete in this repo at the moment. I also recommend you set up the EB environment last. Get the VPC, SGs, RDS, EBS all created first, then tie them to your EB environment by envvars before running `eb deploy` for the first time. Saves a lot of hassle.

The best way you could help is to report any issues you have.

Some todo items on my plate:
1. Configure and test APCu, and Memcache (as a second tier cache).
2. Add optional support for an Aurora cluster (read and write hosts) by envvars to allow for automatic RDS scaling.
3. Perform some load tests to find the best EC2 instance type for Mautic at high load, and other perf tweaks. We'll be testing with at least 100,000,000 leads to start, and concurrent traffic of 2~8k hits per minute.
4. Make the initial installation process smoother/automatic. Perhaps it detects that it's a fresh RDS/db and auto-installs?
5. UI/plugin for multi-site configuration (not really a priority requirement, but a nice-to-have).
