### ISSUE TITLE
Question: Autoscaling compatibility ?

### ISSUE THREAD

**Issue by Guibod** [TheDMSGroup/mautic-eb#29]
Hey, my company is looking forward reseting our poorly deployed instance of Mautic after many failure on AWS Elastic Beanstalk. I'd like to validate with you that you solution is compliant with autoscaling.

Fact is that our first attempt failed and inserted random nonsense in the database after we started multiple instance with cronjob capabilities. It ended with many id constraints issues.

Can you explain me how you achieve « make it simple and safe to scale » as our experience was rather catastrophic on Elastic Beanstalk. Is that mainly related to the common EFS instance that you added in the mix, and the forced usage of spool ? 
How do you achieve cron to « self regulate » ? Is there some risks ?

In the meantime, I'll try to dig your code to understand by myself. 

Thanks for this promising work, we're really looking forward using you solution.

**Comment by heathdutton** [comment]
We do autoscale our DB (Aurora db.r3.2xlarge cluster of read/write) and a couple EC2 instances (c5.xlarge). We can also scale up/down DB or EC2s vertically while running in production with few concerns. We have yet to push sessions to Memcache/Redis but that's a likely next step to reduce CSRF complications for logged-in users (you can also disable the feature or jack up sticky sessions).

We're not using the spool ourselves. Instead we use various other services for sending email/sms by way of the Client plugin, SES, Mailchimp, etc. So if you are depending on spool for your email dispersal there will likely be a permanent bottleneck there. We have it in EFS just for the sake of anyone else using this repo who might not be offloading email to services yet. We're just trying to be compatible with as many use-cases as possible. Mostly we use the EFS mount to ensure a bunch of core Mautic features don't get messed up on deployment or scaling, such as email media, uploads and the like.

Cron tasks are only ran by the leading (oldest) instance. There's a "cron" bash alias which runs a custom bash script which discerns if it is the leader and should be running such tasks (check out the aliases in .ebextensions as they can be helpful). The readme touches on this as you have to make sure your EC2 units have permission to check themselves... 

This means that no instance in your EB should be so small that it can't pull dual duty as a background task runner and web head. Eventually we'll spread cron tasks evenly across all instances (by way of a parent daemon/script w/ modulus use), but it's not a concern for us just yet. For now having a beefier EC2 type (with a minimum count of 1) sails smoother than a bunch of lower powered ones (this will change as Mautic core continues to improve).

Some cron tasks are ran by "cronloop" instead. These are tasks that need heavier attention than just being hit once a minute. They run continuously with a 10s delay between runs, and they make sure they aren't duplicates each time by `ps aux`. For these `cronloop` tasks, there's a cron task just makes sure it always running. Segment updates and campaign triggers often need that tight loop. These cron tasks do not currently self-regulate, so we have them set for the maximum planned need, which is the safest option for now.

There's a "worker count" environment variable specifically for the `mautic:campaign:trigger` job so that we can run more than one concurrent process (using the latest `dev-custom` branch + patches). That's been the biggest bottleneck for us, so we run up to 10 of those concurrently, and that brings the PHP memory limit into play. So you want to do a little math when determining the EC2 instance size you want to run... You want to make sure that (the number of concurrent cron tasks) * (your max php memory) does not exceed the ram on your instances, because those tasks may run for hours on end at heavy load. If they consume all system memory the instance will become non-responsive, so it's better to lower the ram limit and let the cron tasks fail when they hit the limit (which they do fairly gracefully), and restart at the next cron or loop.

On one important note: We ride on the bleeding edge, and depend on a few core PRs that aren't yet merged into Mautic core. You can find/apply those patches with `./scripts/core-patches.sh`. Some of those patches make our scaling possible, and most (if not all) will be merged in by the time Mautic reaches `2.14.2`. This includes fixed support for --threads when running `mautic:campaign:triggers`, fixed support for master/slave db, and other helpful performance tweaks.

In a future update to mautic-eb we'll likely be making these patches part of `composer install` because they are so integral to performance w/ millions of leads.

One bridge we haven't crossed yet is adding beanstalkd to the mix for offloading page hits (and other dispositions). We don't currently use that part of Mautic much, but it'd be a small amount of lift to support here.

Thanks for the questions. Keep 'em coming, as this helps me to know what I *should* be doing with the readme. Also, if you find issues please report or PR. We'd like to see more Mautic users in AWS.

**Comment by Guibod** [comment]
Well thanks for that very precise input. I'll now be able to cope with my initial contact with your base code.

I guess I'll come back to you very soon.
