### ISSUE TITLE
`dev-custom` branch stability issue 

### ISSUE THREAD

**Issue by Guibod** [TheDMSGroup/mautic-eb#35]
Hi, again,

I'm trying to use the 'dev-custom' branch that relies on patches. But the patches in `core-patches.sh` fails at many occasions. 
How does work the patching system ?
Are we applying patches (gist, diffs) that mutates on constant code base (composer) ? or are we applying constant patches on a code base ?

Why, `core-patches.sh` needs to be run manually after installation ? This manual part impedes autoscaling to run effectively, right ?

Should I avoid using this branch at all until stabilized ?

**Comment by Guibod** [comment]
Shouldn't the `composer.json` define a specific master branch revision, instead of installing the very latest master commit ?

**Comment by heathdutton** [comment]
Those patches are only for you if you're using a commit from staging (prior to deployment). If you don't need those patches, don't run them. :)

We're using the staging (2.13.2-dev+) and those patches because it's more stable right now at our scale (millions of leads) than 2.13.2 and below. The multi-threaded cron tasks (for example) currently depend on latest staging. This is a temporary situation till 2.14.0 is official. The 2.14.0 release is a MAJOR refactor of campaigns and segments, and we simply couldn't wait to get those perf benefits... That's why we're on the bleeding edge right now. This is temporary.

After 2.14.0 we'll re-cut the master branch (and dev-custom will be deprecated). We'll then be posting releases of mautic-eb that exactly line up with the mautic releases, with a version lock etc.
